<?php
    if ( ! function_exists( 'custom_post_type' ) ) {
        /**
         * Registers custom post types for the theme.
         *
         * This function registers multiple custom post types including:
         * - Services
         * - Events
         * - Attendees
         * - FAQs
         * - Testimonials
         *
         * It should be hooked to 'init' action.
         */
        function custom_post_type() {

            $labels = array(
                'name'                  => _x( 'Bejegyzéstípusok', 'Post Type General Name', TEXT_DOMAIN ),
                'singular_name'         => _x( 'Bejegyzéstípus', 'Post Type Singular Name', TEXT_DOMAIN ),
                'menu_name'             => __( 'Bejegyzéstípusok', TEXT_DOMAIN ),
                'name_admin_bar'        => __( 'Bejegyzéstípus', TEXT_DOMAIN ),
                'archives'              => __( 'Elem archívum', TEXT_DOMAIN ),
                'attributes'            => __( 'Elem attribútumok', TEXT_DOMAIN ),
                'parent_item_colon'     => __( 'Szülő elem:', TEXT_DOMAIN ),
                'all_items'             => __( 'Összes elem', TEXT_DOMAIN ),
                'add_new_item'          => __( 'Új elem hozzáadása', TEXT_DOMAIN ),
                'add_new'               => __( 'Új bejegyzéstípus', TEXT_DOMAIN ),
                'new_item'              => __( 'Új elem', TEXT_DOMAIN ),
                'edit_item'             => __( 'Elem szerkesztése', TEXT_DOMAIN ),
                'update_item'           => __( 'Elem frissítése', TEXT_DOMAIN ),
                'view_item'             => __( 'Elem megtekintése', TEXT_DOMAIN ),
                'view_items'            => __( 'Elemek megtekintése', TEXT_DOMAIN ),
                'search_items'          => __( 'Elem keresése', TEXT_DOMAIN ),
                'not_found'             => __( 'Nem található', TEXT_DOMAIN ),
                'not_found_in_trash'    => __( 'Nem található a kukában', TEXT_DOMAIN ),
                'featured_image'        => __( 'Kiemelt kép', TEXT_DOMAIN ),
                'set_featured_image'    => __( 'Kiemelt kép beállítása', TEXT_DOMAIN ),
                'remove_featured_image' => __( 'Kiemelt kép eltávolítása', TEXT_DOMAIN ),
                'use_featured_image'    => __( 'Használat kiemelt képként', TEXT_DOMAIN ),
                'insert_into_item'      => __( 'Beszúrás az elembe', TEXT_DOMAIN ),
                'uploaded_to_this_item' => __( 'Feltöltve ehhez az elemhez', TEXT_DOMAIN ),
                'items_list'            => __( 'Elemlista', TEXT_DOMAIN ),
                'items_list_navigation' => __( 'Elemlista navigáció', TEXT_DOMAIN ),
                'filter_items_list'     => __( 'Elemlista szűrése', TEXT_DOMAIN ),
            );
            $args = array(
                'label'                 => __( 'Bejegyzéstípus', TEXT_DOMAIN ),
                'description'           => __( 'Bejegyzéstípus leírása', TEXT_DOMAIN ),
                'labels'                => $labels,
                'supports'              => array( 'title', 'editor' ),
                'taxonomies'            => array( 'category', 'post_tag' ),
                'hierarchical'          => false,
                'public'                => true,
                'show_ui'               => true,
                'show_in_menu'          => true,
                'menu_position'         => 5,
                'show_in_admin_bar'     => true,
                'show_in_nav_menus'     => true,
                'can_export'            => true,
                'has_archive'           => true,
                'exclude_from_search'   => false,
                'publicly_queryable'    => true,
                'capability_type'       => 'post',
            );
            //register_post_type( 'post_type_name', $args );

            $serviceLabels = array(
                'name'                  => _x( 'Szolgáltatások', 'Általános név', TEXT_DOMAIN ),
                'singular_name'         => _x( 'Szolgáltatás', 'Egyes számú név', TEXT_DOMAIN ),
                'menu_name'             => __( 'Szolgáltatások', TEXT_DOMAIN ),
                'name_admin_bar'        => __( 'Szolgáltatás', TEXT_DOMAIN ),
                'archives'              => __( 'Szolgáltatások', TEXT_DOMAIN ),
                'attributes'            => __( 'Szolgáltatás attribútumok', TEXT_DOMAIN ),
                'parent_item_colon'     => __( 'Szülő szolgáltatás:', TEXT_DOMAIN ),
                'all_items'             => __( 'Összes szolgáltatás', TEXT_DOMAIN ),
                'add_new_item'          => __( 'Új szolgáltatás hozzáadása', TEXT_DOMAIN ),
                'add_new'               => __( 'Új', TEXT_DOMAIN ),
                'new_item'              => __( 'Új szolgáltatás', TEXT_DOMAIN ),
                'edit_item'             => __( 'Szolgáltatás szerkesztése', TEXT_DOMAIN ),
                'update_item'           => __( 'Szolgáltatás frissítése', TEXT_DOMAIN ),
                'view_item'             => __( 'Szolgáltatás megtekintése', TEXT_DOMAIN ),
                'view_items'            => __( 'Szolgáltatások megtekintése', TEXT_DOMAIN ),
                'search_items'          => __( 'Szolgáltatás keresése', TEXT_DOMAIN ),
                'not_found'             => __( 'Nem található', TEXT_DOMAIN ),
                'not_found_in_trash'    => __( 'Nem található a kukában', TEXT_DOMAIN ),
                'featured_image'        => __( 'Kiemelt kép', TEXT_DOMAIN ),
                'set_featured_image'    => __( 'Kiemelt kép beállítása', TEXT_DOMAIN ),
                'remove_featured_image' => __( 'Kiemelt kép eltávolítása', TEXT_DOMAIN ),
                'use_featured_image'    => __( 'Kiemelt képként használ', TEXT_DOMAIN ),
                'insert_into_item'      => __( 'Beszúrás a szolgáltatásba', TEXT_DOMAIN ),
                'uploaded_to_this_item' => __( 'Feltöltve ehhez a szolgáltatáshoz', TEXT_DOMAIN ),
                'items_list'            => __( 'Szolgáltatások listája', TEXT_DOMAIN ),
                'items_list_navigation' => __( 'Szolgáltatások listájának navigációja', TEXT_DOMAIN ),
                'filter_items_list'     => __( 'Szolgáltatások listájának szűrése', TEXT_DOMAIN ),
            );
            $serviceArgs = array(
                'label'                 => __( 'Szolgáltatás', TEXT_DOMAIN ),
                'description'           => __( 'A cég által kínált szolgáltatások', TEXT_DOMAIN ),
                'labels'                => $serviceLabels,
                'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
                'taxonomies'            => array( 'service_cat' ),
                'hierarchical'          => false,
                'public'                => true,
                'show_ui'               => true,
                'show_in_menu'          => true,
                'menu_position'         => 5,
                'show_in_admin_bar'     => true,
                'show_in_nav_menus'     => true,
                'can_export'            => true,
                'has_archive'           => true,
                'exclude_from_search'   => false,
                'publicly_queryable'    => true,
                'capability_type'       => 'post',
                'rewrite'               => array( 'slug' => 'szolgaltatasok' ),
                'menu_icon'             => 'dashicons-store',
            );
            register_post_type( 'service', $serviceArgs );

            $kbLabels = array(
                'name'                  => _x( 'Tudásbázis', 'Általános név', TEXT_DOMAIN ),
                'singular_name'         => _x( 'Cikk', 'Egyes számú név', TEXT_DOMAIN ),
                'menu_name'             => __( 'Tudásbázis', TEXT_DOMAIN ),
                'name_admin_bar'        => __( 'Cikk', TEXT_DOMAIN ),
                'archives'              => __( 'Tudásbázis archívum', TEXT_DOMAIN ),
                'attributes'            => __( 'Cikk attribútumok', TEXT_DOMAIN ),
                'parent_item_colon'     => __( 'Szülő cikk:', TEXT_DOMAIN ),
                'all_items'             => __( 'Összes cikk', TEXT_DOMAIN ),
                'add_new_item'          => __( 'Új cikk hozzáadása', TEXT_DOMAIN ),
                'add_new'               => __( 'Új', TEXT_DOMAIN ),
                'new_item'              => __( 'Új cikk', TEXT_DOMAIN ),
                'edit_item'             => __( 'Cikk szerkesztése', TEXT_DOMAIN ),
                'update_item'           => __( 'Cikk frissítése', TEXT_DOMAIN ),
                'view_item'             => __( 'Cikk megtekintése', TEXT_DOMAIN ),
                'view_items'            => __( 'Cikkek megtekintése', TEXT_DOMAIN ),
                'search_items'          => __( 'Cikk keresése', TEXT_DOMAIN ),
                'not_found'             => __( 'Nem található', TEXT_DOMAIN ),
                'not_found_in_trash'    => __( 'Nem található a kukában', TEXT_DOMAIN ),
                'featured_image'        => __( 'Kiemelt kép', TEXT_DOMAIN ),
                'set_featured_image'    => __( 'Kiemelt kép beállítása', TEXT_DOMAIN ),
                'remove_featured_image' => __( 'Kiemelt kép eltávolítása', TEXT_DOMAIN ),
                'use_featured_image'    => __( 'Kiemelt képként használ', TEXT_DOMAIN ),
                'insert_into_item'      => __( 'Beszúrás a cikkbe', TEXT_DOMAIN ),
                'uploaded_to_this_item' => __( 'Feltöltve ehhez a cikkhez', TEXT_DOMAIN ),
                'items_list'            => __( 'Cikkek listája', TEXT_DOMAIN ),
                'items_list_navigation' => __( 'Cikkek listájának navigációja', TEXT_DOMAIN ),
                'filter_items_list'     => __( 'Cikkek listájának szűrése', TEXT_DOMAIN ),
            );

            // Knowledge Base Arguments
            $kbArgs = array(
                'label'                 => __( 'Cikk', TEXT_DOMAIN ),
                'description'           => __( 'Tudásbázis cikkek', TEXT_DOMAIN ),
                'labels'                => $kbLabels,
                'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
                'taxonomies'            => array( 'post_tag', 'knowledge_base_cat' ),
                'hierarchical'          => false,
                'public'                => true,
                'show_ui'               => true,
                'show_in_menu'          => true,
                'menu_position'         => 6,
                'show_in_admin_bar'     => true,
                'show_in_nav_menus'     => true,
                'can_export'            => true,
                'has_archive'           => true,
                'exclude_from_search'   => false,
                'publicly_queryable'    => true,
                'capability_type'       => 'post',
                'rewrite'               => array( 'slug' => 'tudasbazis' ),
                'menu_icon'             => 'dashicons-welcome-learn-more',
            );

            register_post_type( 'knowledge_base', $kbArgs );


            $eventLabels = array(
                'name'                  => _x( 'Események', 'Post Type General Name', TEXT_DOMAIN ),
                'singular_name'         => _x( 'Esemény', 'Post Type Singular Name', TEXT_DOMAIN ),
                'menu_name'             => __( 'Események', TEXT_DOMAIN ),
                'name_admin_bar'        => __( 'Esemény', TEXT_DOMAIN ),
                'archives'              => __( 'Események', TEXT_DOMAIN ),
                'attributes'            => __( 'Esemény attribútumok', TEXT_DOMAIN ),
                'parent_item_colon'     => __( 'Szülő esemény:', TEXT_DOMAIN ),
                'all_items'             => __( 'Összes esemény', TEXT_DOMAIN ),
                'add_new_item'          => __( 'Új esemény hozzáadása', TEXT_DOMAIN ),
                'add_new'               => __( 'Új esemény', TEXT_DOMAIN ),
                'new_item'              => __( 'Új esemény', TEXT_DOMAIN ),
                'edit_item'             => __( 'Esemény szerkesztése', TEXT_DOMAIN ),
                'update_item'           => __( 'Esemény frissítése', TEXT_DOMAIN ),
                'view_item'             => __( 'Esemény megtekintése', TEXT_DOMAIN ),
                'view_items'            => __( 'Események megtekintése', TEXT_DOMAIN ),
                'search_items'          => __( 'Események keresése', TEXT_DOMAIN ),
                'not_found'             => __( 'Nincs találat', TEXT_DOMAIN ),
                'not_found_in_trash'    => __( 'Nincs találat a kukában', TEXT_DOMAIN ),
                'featured_image'        => __( 'Kiemelt kép', TEXT_DOMAIN ),
                'set_featured_image'    => __( 'Kiemelt kép beállítása', TEXT_DOMAIN ),
                'remove_featured_image' => __( 'Kiemelt kép eltávolítása', TEXT_DOMAIN ),
                'use_featured_image'    => __( 'Kiemelt képként használ', TEXT_DOMAIN ),
                'insert_into_item'      => __( 'Beszúrás az eseménybe', TEXT_DOMAIN ),
                'uploaded_to_this_item' => __( 'Feltöltve ehhez az eseményhez', TEXT_DOMAIN ),
                'items_list'            => __( 'Események listája', TEXT_DOMAIN ),
                'items_list_navigation' => __( 'Események lista navigáció', TEXT_DOMAIN ),
                'filter_items_list'     => __( 'Események szűrése', TEXT_DOMAIN ),
            );

            $eventArgs = array(
                'label'                 => __( 'Esemény', TEXT_DOMAIN ),
                'description'           => __( 'Esemény leírása', TEXT_DOMAIN ),
                'labels'                => $eventLabels,
                'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
                'taxonomies'            => array( 'post_tag', 'event_cat' ),
                'hierarchical'          => false,
                'public'                => true,
                'show_ui'               => true,
                'show_in_menu'          => true,
                'menu_position'         => 5,
                'show_in_admin_bar'     => true,
                'show_in_nav_menus'     => true,
                'can_export'            => true,
                'has_archive'           => true,
                'exclude_from_search'   => false,
                'publicly_queryable'    => true,
                'capability_type'       => 'post',
                'rewrite'               => array( 'slug' => 'esemenyek' ),
                'menu_icon'             => 'dashicons-calendar-alt',
            );
            register_post_type('event', $eventArgs);

            $attendeeLabels = array(
                'name'                  => _x( 'Résztvevők', 'Post type general name', TEXT_DOMAIN ),
                'singular_name'         => _x( 'Résztvevő', 'Post type singular name', TEXT_DOMAIN ),
                'menu_name'             => __( 'Résztvevők', 'Admin Menu text', TEXT_DOMAIN ),
                'name_admin_bar'        => __( 'Résztvevő', 'Add New on Toolbar', TEXT_DOMAIN ),
                'add_new'               => __( 'Új résztvevő hozzáadása', TEXT_DOMAIN ),
                'add_new_item'          => __( 'Új résztvevő hozzáadása', TEXT_DOMAIN ),
                'new_item'              => __( 'Új résztvevő', TEXT_DOMAIN ),
                'edit_item'             => __( 'Résztvevő szerkesztése', TEXT_DOMAIN ),
                'view_item'             => __( 'Résztvevő megtekintése', TEXT_DOMAIN ),
                'all_items'             => __( 'Összes résztvevő', TEXT_DOMAIN ),
                'search_items'          => __( 'Résztvevők keresése', TEXT_DOMAIN ),
                'parent_item_colon'     => __( 'Szülő résztvevők:', TEXT_DOMAIN ),
                'not_found'             => __( 'Nincs résztvevő.', TEXT_DOMAIN ),
                'not_found_in_trash'    => __( 'Nincs résztvevő a kukában.', TEXT_DOMAIN ),
            );

            $attendeeArgs = array(
                'label'                 => __( 'Résztvevő', TEXT_DOMAIN ),
                'description'           => __( 'Résztvevő leírása', TEXT_DOMAIN ),
                'labels'                => $attendeeLabels,
                'supports'              => array( 'title' ),
                'taxonomies'            => array(),
                'hierarchical'          => false,
                'public'                => false,
                'show_ui'               => true,
                'show_in_menu'          => true,
                'menu_position'         => 5,
                'show_in_admin_bar'     => true,
                'show_in_nav_menus'     => true,
                'can_export'            => true,
                'has_archive'           => false,
                'exclude_from_search'   => true,
                'publicly_queryable'    => false,
                'capability_type'       => 'post',
                'rewrite'               => array(),
                'menu_icon'             => 'dashicons-tickets',
            );
        
            register_post_type('attendee', $attendeeArgs);

            $faqLabels = array(
                'name'                  => _x( 'Gyakori kérdések', 'Post Type General Name', TEXT_DOMAIN ),
                'singular_name'         => _x( 'Gyakori kérdés', 'Post Type Singular Name', TEXT_DOMAIN ),
                'menu_name'             => __( 'Gyakori kérdések', TEXT_DOMAIN ),
                'name_admin_bar'        => __( 'Gyakori kérdés', TEXT_DOMAIN ),
                'archives'              => __( 'Gyakori kérdések', TEXT_DOMAIN ),
                'attributes'            => __( 'Gyakori kérdés attribútumok', TEXT_DOMAIN ),
                'parent_item_colon'     => __( 'Szülő gyakori kérdés:', TEXT_DOMAIN ),
                'all_items'             => __( 'Összes gyakori kérdés', TEXT_DOMAIN ),
                'add_new_item'          => __( 'Új gyakori kérdés hozzáadása', TEXT_DOMAIN ),
                'add_new'               => __( 'Új gyakori kérdés', TEXT_DOMAIN ),
                'new_item'              => __( 'Új gyakori kérdés', TEXT_DOMAIN ),
                'edit_item'             => __( 'Gyakori kérdés szerkesztése', TEXT_DOMAIN ),
                'update_item'           => __( 'Gyakori kérdés frissítése', TEXT_DOMAIN ),
                'view_item'             => __( 'Gyakori kérdés megtekintése', TEXT_DOMAIN ),
                'view_items'            => __( 'Gyakori kérdések megtekintése', TEXT_DOMAIN ),
                'search_items'          => __( 'Gyakori kérdések keresése', TEXT_DOMAIN ),
                'not_found'             => __( 'Nincs gyakori kérdés találat', TEXT_DOMAIN ),
                'not_found_in_trash'    => __( 'Nincs gyakori kérdés a kukában', TEXT_DOMAIN ),
                'featured_image'        => __( 'Kiemelt kép', TEXT_DOMAIN ),
                'set_featured_image'    => __( 'Kiemelt kép beállítása', TEXT_DOMAIN ),
                'remove_featured_image' => __( 'Kiemelt kép eltávolítása', TEXT_DOMAIN ),
                'use_featured_image'    => __( 'Kiemelt képként használ', TEXT_DOMAIN ),
                'insert_into_item'      => __( 'Beszúrás a gyakori kérdésbe', TEXT_DOMAIN ),
                'uploaded_to_this_item' => __( 'Feltöltve ehhez a gyakori kérdéshez', TEXT_DOMAIN ),
                'items_list'            => __( 'Gyakori kérdések listája', TEXT_DOMAIN ),
                'items_list_navigation' => __( 'Gyakori kérdések lista navigáció', TEXT_DOMAIN ),
                'filter_items_list'     => __( 'Gyakori kérdések lista szűrése', TEXT_DOMAIN ),
            );

            $faqArgs = array(
                'label'                 => __( 'Gyakori kérdés', TEXT_DOMAIN ),
                'description'           => __( 'Gyakori kérdés leírása', TEXT_DOMAIN ),
                'labels'                => $faqLabels,
                'supports'              => array( 'title', 'editor' ),
                'taxonomies'            => array(),
                'hierarchical'          => false,
                'public'                => false,
                'show_ui'               => true,
                'show_in_menu'          => true,
                'menu_position'         => 5,
                'show_in_admin_bar'     => true,
                'show_in_nav_menus'     => true,
                'can_export'            => true,
                'has_archive'           => false,
                'exclude_from_search'   => true,
                'publicly_queryable'    => false,
                'capability_type'       => 'post',
                'rewrite'               => array(),
                'menu_icon'             => 'dashicons-editor-help',
            );
            register_post_type( 'faq', $faqArgs );

        }
        add_action( 'init', 'custom_post_type', 0 );
    }
    